[package]
name = "ut"
edition = "2021"
version = "0.21.0"

[lib]
crate-type = ["rlib", "dylib", "staticlib"]

[dependencies]

[dev-dependencies]
obj-exporter = "*"
clap = { version = "3.1.0", features = ["derive"] }
kiss3d = "0.32"
nalgebra   = { version = "0.29", features = ["rand"] }
